addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.16")
//addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.4.2")
//addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.9.25")
addSbtPlugin("com.dwijnand"      % "sbt-dynver"      % "4.1.1")
addSbtPlugin("com.geirsson"      % "sbt-ci-release"  % "1.5.3")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "5.6.0")